# Generated by Django 5.2.16 on 2026-07-24 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_rendezvous_in_waiting_room_rendezvous_room_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_age', models.CharField(default='30 ans', max_length=20, verbose_name='Âge du patient')),
                ('diagnostic', models.TextField(verbose_name='Diagnostic Médical')),
                ('prescription_details', models.TextField(verbose_name='Prescriptions / Médicaments (Rx)')),
                ('date', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('rendez_vous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnance', to='consultations.rendezvous', verbose_name='Rendez-vous associé')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
                'ordering': ['-created_at'],
            },
        ),
    ]
