# Generated by Django 5.2.16 on 2026-08-10 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Fransick', max_length=100, verbose_name="Nom de l'application")),
                ('hero_text', models.TextField(default='La santé à portée de main', verbose_name="Texte d'accroche (Accueil)")),
                ('primary_color', models.CharField(default='#1B5FA8', max_length=7, verbose_name='Couleur principale (Hex)')),
                ('secondary_color', models.CharField(default='#6DBE45', max_length=7, verbose_name='Couleur secondaire (Hex)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='appearance/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='appearance/', verbose_name='Favicon')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apparence du site',
                'verbose_name_plural': 'Apparence du site',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('about', 'À propos'), ('cgu', "Conditions Générales d'Utilisation"), ('privacy', 'Politique de Confidentialité')], max_length=20, unique=True, verbose_name='Type de page')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la page')),
                ('content', models.TextField(verbose_name='Contenu HTML')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Statique',
                'verbose_name_plural': 'Pages Statiques',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action effectuée')),
                ('target', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cible (ex: ID Utilisateur)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du signalement')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu')], default='new', max_length=20, verbose_name='Statut')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name="Réponse de l'administration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur signalé')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
            },
        ),
    ]
