# Generated by Django 5.2.16 on 2026-08-10 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='target',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('connexion', 'Connexion / Déconnexion'), ('inscription', 'Inscription'), ('profil', 'Modification de profil'), ('recherche', 'Recherche de médecin'), ('consultation', 'Consultation (RDV)'), ('ordonnance', 'Ordonnance'), ('document', 'Document justificatif'), ('catalogue', 'Catalogue de pharmacie'), ('ia', 'Assistant IA'), ('signalement', 'Signalement'), ('admin', 'Action Administrateur'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name="Type d'action"),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reports/attachments/', verbose_name='Pièce jointe'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('technique', 'Problème technique'), ('comportement', 'Comportement utilisateur'), ('litige', 'Litige de commande/consultation'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Type de signalement'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='contact_address',
            field=models.CharField(default='123 Rue de la Santé, 75000 Paris', max_length=255, verbose_name='Adresse de contact'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='contact_email',
            field=models.EmailField(default='support@fransick.com', max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='contact_phone',
            field=models.CharField(default='+33 1 23 45 67 89', max_length=20, verbose_name='Téléphone de contact'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='enable_ia_assistant',
            field=models.BooleanField(default=True, verbose_name="Activer l'assistant IA"),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='enable_payments',
            field=models.BooleanField(default=False, verbose_name='Activer le module de paiement (si disponible)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Facebook'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='hero_description',
            field=models.TextField(default='Gérez vos consultations, ordonnances et rendez-vous médicaux en un seul endroit.', verbose_name='Description courte (Accueil)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='appearance/', verbose_name='Image principale (Accueil)'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Instagram'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn'),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name="Mode maintenance (désactive l'accès aux utilisateurs non-admins)"),
        ),
        migrations.AddField(
            model_name='siteappearance',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Twitter (X)'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=255, verbose_name="Description de l'action"),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='hero_text',
            field=models.CharField(default='La santé à portée de main', max_length=200, verbose_name="Texte d'accroche (Accueil)"),
        ),
    ]
