# Generated by Django 5.2.16 on 2026-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_activitylog_admin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteappearance',
            name='report_suspension_threshold',
            field=models.PositiveIntegerField(default=6, verbose_name='Seuil de signalements pour suspension auto'),
        ),
    ]
