# Generated by Django 5.2.16 on 2026-08-13 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name="Nom de l'appareil")),
                ('is_connected', models.BooleanField(default=True, verbose_name='Connecté')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de connexion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appareil Connecté',
                'verbose_name_plural': 'Appareils Connectés',
            },
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital_type', models.CharField(choices=[('heart_rate', 'Fréquence Cardiaque'), ('blood_pressure', 'Tension Artérielle'), ('oxygen_saturation', 'Saturation en Oxygène (SpO2)'), ('steps', 'Nombre de Pas')], max_length=50, verbose_name='Type de constante')),
                ('value', models.FloatField(verbose_name='Valeur')),
                ('unit', models.CharField(help_text='ex: bpm, mmHg, %, pas', max_length=20, verbose_name='Unité')),
                ('source', models.CharField(default='Montre Connectée', max_length=100, verbose_name='Source des données')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de la mesure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Constante Vitale',
                'verbose_name_plural': 'Constantes Vitales',
                'ordering': ['-timestamp'],
            },
        ),
    ]
