# Generated by Django 5.2.16 on 2026-09-15 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0004_rendezvous_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('acompte_rdv', 'Acompte Rendez-vous (20%)'), ('consultation_directe', 'Consultation Directe (100%)'), ('solde', 'Solde Restant (80%)')], max_length=50, verbose_name='Type de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('successful', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('reference_campay', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Référence CamPay')),
                ('external_reference', models.CharField(max_length=255, unique=True, verbose_name='Référence Externe (Interne à la plateforme)')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone Mobile Money')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='consultations.rendezvous', verbose_name='Rendez-vous associé')),
            ],
            options={
                'verbose_name': 'Transaction de Paiement',
                'verbose_name_plural': 'Transactions de Paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
