# Generated by Django 5.2.16 on 2026-09-15 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_remove_rendezvous_payment_status'),
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Référence interne')),
                ('montant_total_consultation', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tarif total de la consultation (XAF)')),
                ('montant_paye', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant réellement débité (XAF)')),
                ('pourcentage_acompte', models.PositiveIntegerField(default=20, verbose_name="Pourcentage d'acompte")),
                ('payment_type', models.CharField(choices=[('acompte', 'Acompte RDV (20%)'), ('total', 'Paiement Total (Consultation Directe)')], default='acompte', max_length=20, verbose_name='Type de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('successful', 'Succès'), ('failed', 'Échoué'), ('expired', 'Expiré')], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro Mobile Money du payeur')),
                ('campay_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Référence CamPay (transaction)')),
                ('campay_operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='Opérateur (MTN/Orange)')),
                ('campay_raw_response', models.JSONField(blank=True, null=True, verbose_name='Réponse brute CamPay')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement confirmé')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_recus', to=settings.AUTH_USER_MODEL, verbose_name='Médecin bénéficiaire')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Patient payeur')),
                ('rdv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='consultations.rendezvous', verbose_name='Rendez-vous lié')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
