# Generated by Django 5.2.16 on 2026-09-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_paiement_delete_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name="Message d'erreur (lisible patient)"),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='campay_raw_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Réponse brute CamPay (nettoyée, sans données sensibles)'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('successful', 'Succès'), ('failed', 'Échoué'), ('expired', 'Expiré'), ('cancelled', 'Annulé par le patient')], default='pending', max_length=20, verbose_name='Statut du paiement'),
        ),
    ]
