# Generated by Django 5.2.16 on 2026-07-22 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du médicament')),
                ('dosage', models.CharField(max_length=50, verbose_name='Dosage')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Indications / Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('pharmacies', models.ManyToManyField(limit_choices_to={'role': 'pharmacie'}, related_name='medicaments', to=settings.AUTH_USER_MODEL, verbose_name='Disponible dans ces pharmacies')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=255, verbose_name='Nom de la pharmacie')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('is_on_duty', models.BooleanField(default=False, verbose_name='Pharmacie de garde 🏥')),
                ('opening_hours', models.CharField(default='08:00 - 22:00', max_length=100, verbose_name="Horaires d'ouverture")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
