# Generated by Django 5.2.16 on 2026-08-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='is_on_duty',
            field=models.BooleanField(default=False, verbose_name='Pharmacie de garde'),
        ),
    ]
