# Generated by Django 5.2.16 on 2026-08-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_alter_pharmacyprofile_is_on_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprofile',
            name='autorisation_exercice',
            field=models.FileField(blank=True, null=True, upload_to='pharmacy_documents/autorisations/', verbose_name="Autorisation d'exercice"),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name="Compte validé par l'admin"),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='registre_commerce',
            field=models.FileField(blank=True, null=True, upload_to='pharmacy_documents/registres/', verbose_name='Registre de commerce'),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motif du refus'),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de demande'),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('verified', 'Validé'), ('rejected', 'Refusé')], default='verified', max_length=20, verbose_name='Statut de validation'),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation/rejet'),
        ),
    ]
