# Generated by Django 5.2.16 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un utilisateur avec cette adresse email existe déjà.'}, max_length=254, unique=True, verbose_name='adresse email'),
        ),
    ]
