# Generated by Django 5.2.16 on 2026-08-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dark_mode_enabled',
            field=models.BooleanField(default=False, verbose_name='Mode sombre activé'),
        ),
    ]
