# Generated by Django 5.2.16 on 2026-07-20 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('video', 'Téléconsultation Vidéo 🎥'), ('audio', 'Téléconsultation Audio 🎙️'), ('cabinet', 'Consultation en Cabinet 🏥')], default='video', max_length=20, verbose_name='Type de consultation')),
                ('date', models.DateField(verbose_name='Date du RDV')),
                ('time_slot', models.CharField(max_length=20, verbose_name='Créneau horaire (ex: 10:00)')),
                ('reason', models.CharField(max_length=255, verbose_name='Motif de la consultation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Symptômes / Remarques du patient')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmé'), ('pending', 'En attente'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time_slot'],
            },
        ),
    ]
