# Generated by Django 5.2.16 on 2026-07-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='in_waiting_room',
            field=models.BooleanField(default=False, verbose_name="Dans la salle d'attente"),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du salon de visio'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmé'), ('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='confirmed', max_length=20),
        ),
    ]
