# Generated by Django 5.2.16 on 2026-08-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_rendezvous_in_waiting_room_rendezvous_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='consultation_type',
            field=models.CharField(choices=[('video', 'Téléconsultation Vidéo'), ('audio', 'Téléconsultation Audio'), ('cabinet', 'Consultation en Cabinet')], default='video', max_length=20, verbose_name='Type de consultation'),
        ),
    ]
