# Generated by Django 5.2.16 on 2026-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_rendezvous_consultation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('partial_paid', 'Acompte payé'), ('full_paid', 'Payé en totalité'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut du paiement'),
        ),
    ]
