# Generated by Django 5.2.16 on 2026-09-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_rendezvous_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='payment_status',
        ),
    ]
