# Generated by Django 5.2.16 on 2026-08-18 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0003_alter_rendezvous_consultation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Nom du canal Agora')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20, verbose_name="Statut de l'appel")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('rendez_vous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appel_video', to='consultations.rendezvous', verbose_name='Rendez-vous associé')),
            ],
            options={
                'verbose_name': 'Appel Vidéo',
                'verbose_name_plural': 'Appels Vidéo',
            },
        ),
    ]
