# Generated by Django 5.2.16 on 2026-08-27 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appelconsultation',
            name='channel_name',
        ),
        migrations.AddField(
            model_name='appelconsultation',
            name='room_code',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Code de la salle Jitsi'),
        ),
    ]
