# Generated by Django 5.2.16 on 2026-07-20 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la capsule')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Légende & Hashtags')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Fichier vidéo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de réactions')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
