# Generated by Django 5.2.16 on 2026-07-20 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(blank=True, max_length=150, null=True, verbose_name='Spécialité médicale')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de licence / ordre')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Présentation / Biographie')),
                ('schedule', models.CharField(blank=True, max_length=255, null=True, verbose_name='Horaires de consultation')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name="Années d'expérience")),
                ('consulted_patients_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de patients consultés')),
                ('clinic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la clinique / cabinet')),
                ('clinic_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse du cabinet')),
                ('clinic_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone du cabinet')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Note moyenne')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers_received', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
