# Generated by Django 5.2.16 on 2026-08-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0003_videocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Note moyenne'),
        ),
    ]
