# Generated by Django 5.2.16 on 2026-08-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0004_alter_doctorprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='diploma_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_documents/diplomas/', verbose_name='Diplôme(s) médical(aux)'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_affiliation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Hôpital / structure d'exercice"),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_documents/identity/', verbose_name="Pièce d'identité"),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name="Compte validé par l'admin"),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='professional_card_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_documents/cards/', verbose_name='Carte professionnelle / Attestation Ordre'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motif du refus'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de demande'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('verified', 'Validé'), ('rejected', 'Refusé')], default='verified', max_length=20, verbose_name='Statut de validation'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation/rejet'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numéro de licence / ordre'),
        ),
    ]
