# Generated by Django 5.2.16 on 2026-08-11 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0005_doctorprofile_address_doctorprofile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom de la spécialité')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='specialities/icons/', verbose_name='Icône')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Spécialité médicale',
                'verbose_name_plural': 'Spécialités médicales',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='speciality',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Spécialité médicale (Ancien)'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.specialite', verbose_name='Spécialité médicale'),
        ),
    ]
