# Generated by Django 5.2.16 on 2026-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0006_specialite_alter_doctorprofile_speciality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee_direct',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarif Consultation Directe (FCFA)'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee_rdv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tarif Rendez-vous (FCFA)'),
        ),
    ]
