# Generated by Django 5.2.16 on 2026-09-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0007_doctorprofile_consultation_fee_direct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='consultation_fee_direct',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='consultation_fee_rdv',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Tarif de consultation (XAF)'),
        ),
    ]
