# Generated by Django 5.2.16 on 2026-07-24 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=10, null=True, verbose_name='Sexe')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Notes supplémentaires (allergie, diabétique...)')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier')),
                ('occupation', models.CharField(blank=True, max_length=150, null=True, verbose_name='Occupation')),
                ('civil_status', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié'), ('divorce', 'Divorcé'), ('veuf', 'Veuf')], max_length=20, null=True, verbose_name='État civil')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille (en cm)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Poids (en Kg)')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True, verbose_name='Groupe sanguin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
